spring:
  data:
    mongodb:
      uri: ${MONGOURI}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 39539365824-0univubnhd6st88lhonc95rlpm5de51e.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

spring:
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${MAIL_USERNAME} # 3
    password: ${MAIL_PASSWORD} # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7

jwt:
  secret: ${JWT_SECRET:fffffff}
  expiration: 86400000 # 24시간

logging:
  level:
    org.springframework.security: DEBUG
    com.dku.priorify: DEBUG