spring:
  data:
    mongodb:
      uri: ${MONGOURI}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 1000 #1초
      mail.starttls.enable: true
      mail.smtp.auth: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 39539365824-0univubnhd6st88lhonc95rlpm5de51e.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile


jwt:
  secret: ${JWT_SECRET:fffffff}
  expiration: 864000000 # 10일

logging:
  level:
    org.springframework.security: DEBUG
    com.dku.priorify: DEBUG