name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t junseosong/priorify-backend:amd64-latest \
            --push .
            
      - name: Get Jenkins crumb
        id: get_crumb
        run: |
          CRUMB=$(curl -s -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            "${{ secrets.JENKINS_HOST }}/crumbIssuer/api/json" \
            | jq -r .crumb)
          echo "::set-output name=crumb::$CRUMB"

      #Jenkins에 배포 트리거
      - name: Trigger Jenkins Deploy
        run: |
          curl -X POST \
            "${{ secrets.JENKINS_HOST }}/job/priorify-deploy/build?token=${{ secrets.DEPLOY_TOKEN }}"
